# SPDX-FileCopyrightText: 2025 Ryan Cao <hello@ryanccn.dev>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name = "modernflux"
compatibility_date = "2025-04-15"
send_metrics = false

[assets]
directory = "dist"
not_found_handling = "none"
